apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unleash-service.fullname" . }}
  labels:
    {{- include "unleash-service.labels" . | nindent 4 }}

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "unleash-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unleash-service.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unleash-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: unleash-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: 8080
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
          - name: CONFIGURATION_SERVICE
            value: "http://localhost:8081/configuration-service"
          - name: env
            value: 'production'
          {{- if .Values.remoteControlPlane.enabled }}
          - name: KEPTN_API_ENDPOINT
            value: "{{ .Values.remoteControlPlane.api.protocol }}://{{ .Values.remoteControlPlane.api.hostname }}/api"
          - name: KEPTN_API_TOKEN
            value: "{{ .Values.remoteControlPlane.api.token }}"
          - name: EVENTBROKER
            value: "{{ .Values.remoteControlPlane.api.eventbroker }}"
          {{- end }}
          envFrom:
            - secretRef:
                name: unleash
                optional: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}