  {{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unleash-service.serviceAccountName" . }}
  labels:
    {{- include "unleash-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unleash-service
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unleash-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unleash-service
subjects:
  - kind: ServiceAccount
    name: {{ include "unleash-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
    {{- end }}