---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: unleash-sub
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: problem
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: unleash-service
      